# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-adb5263b-f571-4d57-b947-8cfe76f8cbf8";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-adb5263b-f571-4d57-b947-8cfe76f8cbf8".device = "/dev/disk/by-uuid/adb5263b-f571-4d57-b947-8cfe76f8cbf8";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F081-308A";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-6de8cb75-c105-4641-b40d-6184f68e251e"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
